config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'recipes#public_recipes'

  # Defines the root path route ("/")
  # get '/shopping_list', to: 'foods#shopping_list', as: 'shopping_list'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    get '/public_recipes', to: 'recipes#public_recipes'
    delete '/recipes/:id/:food_id', to: 'recipes#remove_food_from_recipe', as: 'recipe_food'


    resources :recipes, only: [:index, :new, :show, :create, :update, :destroy] do
      get '/shopping_list', to: 'foods#shopping_list', as: 'shopping_list'
      resources :recipe_foods, only: [:index, :show, :new, :create]
    end

    resources :foods, only: [:index, :new, :create]

    delete 'foods/:id', to: 'foods#delete', as: 'delete_food'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :public_recipes, Recipe
    can :read, Recipe, public: true

    return unless user.persisted?

    can :manage, Recipe, user_id: user.id
    can :manage, RecipeFood

    can :manage, Food, user_id: user.id

    return unless user.role == 'admin'

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, presence: true, length: { maximum: 250 }
  validates :measurement_unit, presence: true
  validates :price, presence: true
  validates :quantity, presence: true

  belongs_to :user, foreign_key: 'user_id'
  has_many :recipe_foods, dependent: :destroy
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true, length: { maximum: 250 }
  validates :description, presence: true
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :user, foreign_key: 'user_id'
  has_many :recipe_foods, dependent: :destroy
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :recipe, foreign_key: 'recipe_id'
  belongs_to :food, foreign_key: 'food_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :confirmable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 250 }
  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.where({ user_id: current_user.id })
  end

  def new
    @food = Food.new
  end

  def shopping_list
    foods = Food.includes(:recipe_foods).where({ user_id: current_user.id })
    @shopping_list = []
    @total_price = 0
    foods.each do |food|
      shopping_list_item = {
        food: food.name,
        quantity: calculate_missing_food(food),
        unit: food.measurement_unit,
        unit_price: food.price
      }
      @total_price += shopping_list_item[:quantity] * shopping_list_item[:unit_price]
      @shopping_list << shopping_list_item if (shopping_list_item[:quantity]).positive?
    end
  end

  def create
    name = food_params[:name]
    measurement_unit = food_params[:measurement_unit]
    quantity = food_params[:quantity]
    price = food_params[:price]
    food = Food.new(user_id: current_user.id, name:, measurement_unit:, price:, quantity:)

    if food.save
      redirect_to foods_path, notice: 'Food created successfully!'
    else
      render :new, notice: 'An error occured while creating a new food'
    end
  end

  def delete
    @food = Food.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'Food deleted successfully!'
    else
      redirect_to foods_path, alert: 'Unable to delete the food item.'
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end

  def calculate_missing_food(food)
    missing_food = -food.quantity
    food.recipe_foods.each do |recipe_food|
      missing_food += recipe_food.quantity
    end

    return 0 if missing_food <= 0

    missing_food
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  load_and_authorize_resource

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.where(user_id: current_user.id)
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe.id), notice: 'Food added to the recipe successfully.'
    else
      @foods = Food.all
      render :new
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # Load and authorize the appropriate resource for the controller
  load_and_authorize_resource

  def index
    # Used 'includes' method to minimize N+1 Queries:
    @recipes = Recipe.includes(:recipe_foods).where(user_id: current_user.id) if current_user
    @recipes = Recipe.includes(:recipe_foods).where(public: true) unless current_user
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    @recipe_foods = @recipe.recipe_foods
  end

  def create
    name = recipe_params[:name]
    preparation_time = recipe_params[:preparation_time] || 0
    cooking_time = recipe_params[:cooking_time] || 0
    description = recipe_params[:description]
    recipe = Recipe.new(user_id: current_user.id, name:, preparation_time:, description:, cooking_time:)

    if recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def update
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      redirect_to recipe_path(@recipe), notice: 'Recipe could not be upddated'
    end
  end

  def destroy
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])

    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe successfully deleted'
    else
      redirect_to recipes_path, notice: 'Recipe could not be deleted'
    end
  end

  def public_recipes
    @users = User.includes(:recipes).all
    @foods = Food.includes(:recipe_foods).all
    @public_recipes = Recipe.includes(:user, :recipe_foods).where(public: true).order(created_at: :desc)
    @current_user = current_user
  end

  def remove_food_from_recipe
    @recipe_food = RecipeFood.includes(:food).find_by(recipe_id: params[:id], food_id: params[:food_id])
    @recipe_food.destroy
    redirect_to recipe_path(params[:id])
  end

  private
  # Used private method to enforce stringent security measures for browser request parameters
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<tr class="food-item">
    <td><%= food.name%></td>
    <td><%= food.measurement_unit%></td>
    <td><%= food.price%></td>
    <td>
        <% if can? :destroy, Food %>
            <%=  button_to 'Delete', delete_food_path(food.id), method: :delete %>
        <% end %>
    </td>
</tr>

app/views/foods/index.html.erb
<div class="md:w-[70%] mx-auto">
    <h1 class="md:text-4xl text-2xl font-extrabold mx-auto text-center">My Foods</h1>
    <%= render partial: 'shared/header' %>
    <div class="w-full flex justify-end">
        <% if can? :destroy, Food %>
            <a href=<%= new_food_path %> id="add-food-link" class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2">Add Food</a>
        <% end %>
    </div>

    <div class="grid grid-cols-4 grid-rows-1 grid-flow-row border-2 border-black mt-5">
        <div class="font-extrabold bg-gray-400 border-r-2 border-black px-3">Food</div>
        <div class="font-extrabold bg-gray-400 border-r-2 border-black px-3">Measurement unit</div>
        <div class="font-extrabold bg-gray-400 border-r-2 border-black px-3">Unit price</div>
        <div class="font-extrabold bg-gray-400 px-5">Actions</div>
        <% @foods.each do |food| %>
            <div class="border-r-2 border-black px-3"><%= food.name %></div>
            <div class="border-r-2 border-black px-3"><%= food.measurement_unit %></div>
            <div class="border-r-2 border-black px-3"><%= food.price %></div>
            <div class="border-r-2 border-black px-5">
                <% if can? :destroy, Food %>
                    <%=  button_to 'Delete', delete_food_path(food.id), class: "font-medium text-blue-600 underline hover:no-underline", method: :delete %>
                <% end %>
            </div>
        <% end %>
    </div>
</div>


app/views/foods/new.html.erb
<%= render partial: 'shared/header' %>
<div class="w-full flex flex-col justify-center items-center md:w-[60%] mx-auto">
    <div class="flex justify-between w-[100%]">
        <a href="<%= foods_path %>"><i class="fa-solid fa-left-long md:text-4xl text-2xl"></i></a>
        <h1 class="md:text-4xl text-2xl font-extrabold mx-auto">Add Food</h1>
    </div>

    <%= form_with class:'flex flex-col gap-2 w-[100%] mt-5', model: @food, url: { action: "create" }, method: :post do |f| %>
        <%= f.text_field :name, placeholder: 'Food name', class: 'w-full h-[50px] border border-black' %>
        <%= f.text_field :measurement_unit, placeholder: 'measurement unit', class: 'w-full h-[50px] border border-black' %>
        <%= f.number_field :price, placeholder: 'Food price', class: 'w-full h-[50px] border border-black' %>
        <%= f.number_field :quantity, placeholder: 'Food quantity', class: 'w-full h-[50px] border border-black' %>
        <%= f.submit 'ADD FOOD', class: 'w-[120px] text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2' %>
    <% end %>
</div>

app/views/foods/shopping_list.html.erb
<%= render partial: 'shared/header' %>
<div class="md:w-[50%] mx-auto flex flex-col gap-5 items-center">
    <div class="flex justify-between w-[90%]">
        <a href="<%= recipe_path(params[:recipe_id]) %>"><i class="fa-solid fa-left-long md:text-4xl text-2xl"></i></a>
        <h1 class="md:text-4xl text-2xl font-extrabold mx-auto">Shopping list</h1>
    </div>
    

    <div class="flex justify-between w-[90%] mt-5">
        <p>Amount of food to buy: <span class="font-extrabold"><%= @shopping_list.length %></span></p>
        <p>Total value of food needed: <span class="font-extrabold"><%= @total_price %></span></p>
    </div>
    <div class="grid grid-cols-3 grid-rows-1 grid-flow-row border-2 border-black w-[90%]">
        <div class="font-extrabold bg-gray-400 border-r-2 border-black px-3">Food</div>
        <div class="font-extrabold bg-gray-400 border-r-2 border-black px-3">Quantity</div>
        <div class="font-extrabold bg-gray-400 border-r-2 border-black px-3">Price</div>
        <% @shopping_list.each do |shopping_list_item| %>
          <div class="border-r-2 border-black px-3"><%= shopping_list_item[:food] %></div>
          <div class="border-r-2 border-black px-3"><%= "#{shopping_list_item[:quantity]} #{shopping_list_item[:unit]}" %></div>
          <div class="border-r-2 border-black px-3"><%= "#{shopping_list_item[:unit_price] * shopping_list_item[:quantity]} $" %></div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'jquery' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex flex-col">
      <div class="text-color-green font-bold text-center"><%= notice if notice %></div>
      <div class="text-color-red font-bold text-center pb-5"><%= alert if alert %></div>
      <%= yield %>
    </main>

    <script>      
      document.querySelector('#hamburger').addEventListener('click', () => {
        document.querySelector('#menu').classList.toggle('hidden');
        document.querySelector('.fa-solid').classList.toggle('fa-xmark');
      })
      document.querySelectorAll('.hlink').forEach((link) => {
        link.addEventListener('click', () => {
          menu.classList.toggle('hidden');
          document.querySelector('.fa-solid').classList.toggle('fa-xmark');
        })
      })
    </script>
  </body>
</html>

app/views/partials/_header.html.erb
      <header class="sticky top-0 text-white bg-slate-600">
        <nav class="w-[100vw] h-[60px] flex justify-between items-center">
          <h1 class="text-lg font-bold">
            <%= link_to "recipe app", foods_path(current_user.id) %>
          </h1>
          <ul class="flex items-center h-full gap-7">
            <li>
              <%= link_to "recipes", recipes_path(current_user.id) %>
            </li>
            <li>
              <%= link_to "foods", foods_path %>
            </li>
            <li>
              <%= link_to "shopping list", shopping_list_path %>
            </li>
            <li>
              <%= link_to "public recipes", public_recipes_path(current_user.id) %>
            </li>
            <li>
              <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete } %>
            </li>
          </ul>          
        </nav>
      </header>

app/views/recipe_foods/new.html.erb
<%= render partial: 'shared/header' %>
<div class="w-full md:w-[50%] mx-auto gap-5">
  <a href="<%= recipe_path(params[:recipe_id]) %>"><i class="fa-solid fa-left-long md:text-4xl text-2xl"></i></a>
  <div class="mx-auto md:flex md:justify-center text-center">
    <%= form_with model: [@recipe, @recipe_food], url: recipe_recipe_foods_path(@recipe), class: "border w-full", method: :post do |form| %>
      <%= form.collection_select :food_id, @foods, :id, :name, prompt: 'Select a food', class: "border border-red-500" %>
      <%= form.number_field :quantity, placeholder: 'Enter quantity', class: "mt-5" %>
      <%= form.submit 'Add Food', class: "text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 mt-5" %>
  <% end %>
  </div>

</div>

app/views/recipes/index.html.erb
<%= render partial: 'shared/header' %>
<div class="flex flex-col gap-5 w-full md:w-[60%] mx-auto">
  <h1 class="md:text-4xl text-2xl font-extrabold mx-auto">My Recipes</h1>
  <div class="w-full flex justify-end">
    <% if can? :destroy, Recipe %>
        <a href=<%= new_recipe_path %> id="add-food-link" class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2">Add Recipe</a>
    <% end %>
  </div>

  <% @recipes.each do |recipe| %>
    <% if can? :read, recipe %>
      <%= render partial: 'shared/recipe_card', locals: { recipe: recipe } %>
    <% end %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<%= render partial: 'shared/header' %>
<div class="w-full flex flex-col justify-center items-center md:w-[60%] mx-auto">
    <div class="flex justify-between w-[100%]">
        <a href="<%= recipes_path %>"><i class="fa-solid fa-left-long md:text-4xl text-2xl"></i></a>
        <h1 class="md:text-4xl text-2xl font-extrabold mx-auto">Add Recipe</h1>
    </div>
    <%= form_with class:'flex flex-col gap-2 w-[100%] mt-5', model: @recipe, url: { action: "create" }, method: :post do |f| %>
        <%= f.text_field :name, placeholder: 'Recipe name', class: 'w-full h-[50px] border border-black' %>
        <%= f.number_field :preparation_time, step:'0.01', placeholder: 'Preparation time in hour', class: 'w-full h-[50px] border border-black' %>
        <%= f.number_field :cooking_time, step: '0.01', placeholder: 'Cooking time in hour', class: 'w-full h-[50px] border border-black' %>
        <%= f.text_field :description, placeholder: 'Recipe description', class: 'w-full h-[50px] border border-black' %>
        <%= f.submit 'ADD RECIPE', class: 'w-[120px] text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2' %>
        <% if flash[:notice] %>
            <div class="notice">
                <%= flash[:notice] %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/recipes/public_recipes.html.erb
<%= render partial: 'shared/header' %>
<div class="flex flex-col gap-5 w-full md:w-[60%] mx-auto">
  <h1 class="md:text-4xl text-2xl font-extrabold mx-auto">Public Recipes</h1>
  <% @public_recipes.each do |public_recipe| %>
   <%= render partial: 'shared/public_recipe_card', locals: { public_recipe: public_recipe } %>
  <% end %>
  <% if !current_user %>
    <p class="mx-auto">Don't have an account? <span class="font-bold hover:underline"><%= link_to "Sign up", new_user_registration_path %></span></p>
  <% end %>
</div>

app/views/recipes/show.html.erb

<%= render partial: 'shared/header' %>

<div class="w-full flex flex-col gap-5 pl-[3%] pr-[3%] md:w-[60%] mx-auto pt-5">
  <div class="flex justify-between w-[90%]">
    <a href="<%= recipes_path %>"><i class="fa-solid fa-left-long md:text-4xl text-2xl"></i></a>
    <h1 class="md:text-4xl text-2xl font-extrabold mx-auto"><%= @recipe.name %></h1>
  </div>  
  <div class="flex justify-between w-[90%]">
    <p>Preparation time: <span class="font-extrabold"><%= @recipe.preparation_time %> hour(s)</span></p>
    <% if can? :update, @recipe %>
      <%= form_with url: recipe_path(@recipe), data: { "turbo-method": :patch}, model: @recipe do |form| %>
        <div class="relative inline-block w-[50px] mr-2 align-middle select-none transition duration-200 ease-in">
          <%= form.label :public, 'Public' %>
          <%= form.check_box :public, id: "public-checkbox", class: "toggle-checkbox absolute block w-6 h-6 rounded-full bg-white border-4 appearance-none cursor-pointer", onchange: "this.form.submit();" %>
          <label for="toggle" class="toggle-label block overflow-hidden h-6 rounded-full bg-gray-300 cursor-pointer"></label>
        </div>
      <% end %>
    <% end %>

  </div>
  <p>Cooking time: <span class="font-extrabold"><%= @recipe.cooking_time %> hour(s)</span></p>
  <p>Steps go here...</p>

  <% if can? :update, @recipe %>
    <div class="flex justify-between">
      <button class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2">
        <%= link_to 'Generate shopping list', recipe_shopping_list_path(params[:id]) %>
      </button>
      <%= link_to 'Add Food', new_recipe_recipe_food_path(@recipe), class: "text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2" %>
    </div>
  <% end %>

  <div class="w-[90%] border-2 border-black mx-auto"></div>

  <div class="grid grid-cols-4 grid-rows-1 grid-flow-row border-2 border-black">
    <div class="font-extrabold bg-gray-400 border-r-2 border-black px-3">Food</div>
    <div class="font-extrabold bg-gray-400 border-r-2 border-black px-3">Quantity</div>
    <div class="font-extrabold bg-gray-400 border-r-2 border-black px-3">Value</div>
    <div class="font-extrabold bg-gray-400 px-3">Actions</div>
    <% @recipe_foods.each do |recipe_food| %>
      <div class="border-r-2 border-black px-3"><%= Food.find_by(id: recipe_food.food_id).name %></div>
      <div class="border-r-2 border-black px-3"><%= recipe_food.quantity %></div>
      <div class="border-r-2 border-black px-3"><span>$</span><%= Food.find_by(id: recipe_food.food_id).price * recipe_food.quantity %></div>
      
      <div class="md:flex justify-between px-3">
        <% if can? :update, @recipe %>
          <a href="#" class="font-medium text-blue-600 underline hover:no-underline">Modify</a>
          <%= link_to 'Remove', recipe_food_path(@recipe.id, Food.find_by(id: recipe_food.food_id).id), class: "font-medium text-blue-600 underline hover:no-underline", data: { "turbo-method": :delete } %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_header.html.erb
<header>
  <nav class="fixed w-full z-20 top-0 left-0 border-b bg-gray-900 border-gray-600">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
      <div class="flex items-center">
        <img src="/images/logo3.gif" class="h-8 mr-3" alt="Logo">
      </div>

      <div class="flex md:order-2">
        <%= link_to "Log out", destroy_user_session_path, class: "text-white bg-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2 text-center mr-3 md:mr-0", data: { "turbo-method": :delete } if user_signed_in? %>

        <%= link_to "Sign up", new_user_registration_path, class: "text-white bg-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2 text-center mr-3 md:mr-0" if current_page?(new_user_session_path) || alert %>

        <%= link_to "Sign in", new_user_session_path, class: "text-white bg-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2 text-center mr-3 md:mr-0" if !user_signed_in? && !current_page?(new_user_session_path) && !alert %>

        <button id="hamburger" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center rounded-lg md:hidden hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-sticky" aria-expanded="false">
          <i class="fa-solid fa-bars text-2xl text-white"></i>
        </button>
      </div>

      <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="menu">
        <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border rounded-lg md:flex-row md:space-x-8 md:mt-0 md:border-0 bg-gray-800 md:bg-gray-900 border-gray-700">
          <li>
            <a href="<%= public_recipes_path %>" class="block py-2 pl-3 pr-4 rounded md:p-0 md:hover:text-blue-500 text-white hover:bg-gray-700 hover:text-white md:hover:bg-transparent border-gray-700 hlink" aria-current="page">Public Recipes</a>
          </li>
          <% if current_user != nil %>
            <li>
              <a href="<%= recipes_path %>" class="block py-2 pl-3 pr-4 rounded md:p-0 md:hover:text-blue-500 text-white hover:bg-gray-700 hover:text-white md:hover:bg-transparent border-gray-700 hlink">My Recipes</a>
            </li>
            <li>
              <a href="<%= foods_path %>" class="block py-2 pl-3 pr-4 rounded md:p-0 md:hover:text-blue-500 text-white hover:bg-gray-700 hover:text-white md:hover:bg-transparent border-gray-700 hlink">My Foods</a>
            </li>
          <% end %>
        </ul>
      </div>

    </div>
  </nav>
</header>

app/views/shared/_public_recipe_card.html.erb
<div class="border-2 border-black flex p-[3%] justify-between w-[100%] mx-auto relative min-h-[140px]">
  <div>
    <h2 class="font-extrabold"><%= public_recipe.name %></h2>
    <p>by<br> <span><%= @users.find_by(id: public_recipe.user_id).name %></span></p>
  </div>
  <div>
    <p>Total food items: <span class="font-extrabold"><%= public_recipe.recipe_foods.count %></span></p>
    <p>Total price:
      <% total_price = 0 %>
      <% public_recipe.recipe_foods.each do |recipe_foods|  %>
        <% total_price += recipe_foods.quantity * @foods.find_by(id: recipe_foods.food_id).price %>
      <% end %>
      <span class="font-extrabold">$<%= total_price %></span>
    </p>
  </div>
  <a href="<%= recipe_path(public_recipe.id) %>"  id="<%= public_recipe.id %>" class="text-white absolute h-7 md:right-[2%] bottom-1 left-[2%] md:left-auto bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 mt-5 pt-1">Details</a>

</div>

app/views/shared/_recipe_card.html.erb
  <div class="border-2 border-black flex gap-[5%] p-[3%] relative min-h-[140px]">
    <div>
      <h2 class="text-xl font-extrabold"><%= recipe.name %></h2>
      <% if can? :destroy, recipe %>
      <%= link_to 'REMOVE', recipe_path(recipe.id), class: "font-medium text-blue-600 underline hover:no-underline", data: { "turbo-method": :delete } %>
      <% end %>

    </div>
    <div class="w-[65%]">
      <p><%= recipe.description %></p>
    </div>
    <a href="<%= recipe_path(recipe.id) %>" id="<%= recipe.id %>"  class="text-white absolute h-7 md:right-[2%] bottom-1 left-[2%] md:left-auto bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 mt-5 pt-1">Details</a>
  </div>